Log:
  Level: Trace
Bgp:
  Asn: 65531
  Id: "127.0.0.1"
  Listen:
      Ip: "0.0.0.0"
      Port: 8179
  Peers:
    - Asn: 65530
      Address:
        Ip: "192.168.151.44"
        Port: 179
Dns:
  Listen:
    Ip: 0.0.0.0
    Port: 53
  Resolvers:
    - Ip: 77.88.8.8
      Port: 53
    - Ip: 77.88.8.1
      Port: 53
  Cache:
    MinTtl: 10
    MaxEntries: 5
  List:
    File: sample\my.lst
    Resolvers:
      - Ip: 1.1.1.1
        Port: 53
      - Ip: 8.8.8.8
        Port: 53
