Logging:
  Level: Debug
Routing:
  Kernel:
    Inject:
        Communities:
          - 65530:111
  Bgp:
    Asn: 65530
    Id: 192.168.151.250
    Listen:
      Ip: 0.0.0.0
      Port: 1179
    Communities:
      - 65530:888
    Peers:
      - Asn: 65530
        Addr:
         Ip: 192.168.151.41
         Port: 179
  #    - Asn: 65531
  #      Addr:
  #        Ip: 192.168.151.43
#        Port: 179
DefaultResolvers:
  - Ip: 77.88.8.1
    Port: 53
  - Ip: 77.88.8.8
    Port: 53
Resolvers:
  - Ip: 8.8.4.4
    Port: 53
  - Ip: 1.1.1.1
    Port: 53
Responder:
  Ip: 0.0.0.0 # 127.0.0.1
  Port: 8053
Timeouts:
  DefaultTTL: 60
Names:
  - intel.com
  #- yt3.ggpht.com
  #- www.digitalocean.com
  #- digitalocean.com
  #- www.cadillac.com
  #- brands.gm-cdn.com
  #- www.svoboda.org
  #- cloud.ibm.com
  #- ibm.com
  #- www.ibm.com
  #- dataplatform.cloud.ibm.com
