// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/api/bgp-dns.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCacheEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCacheEntriesRequest) Reset() {
	*x = ListCacheEntriesRequest{}
	mi := &file_proto_api_bgp_dns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCacheEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCacheEntriesRequest) ProtoMessage() {}

func (x *ListCacheEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_bgp_dns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCacheEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListCacheEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_bgp_dns_proto_rawDescGZIP(), []int{0}
}

type ClearCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCacheRequest) Reset() {
	*x = ClearCacheRequest{}
	mi := &file_proto_api_bgp_dns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCacheRequest) ProtoMessage() {}

func (x *ClearCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_bgp_dns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCacheRequest.ProtoReflect.Descriptor instead.
func (*ClearCacheRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_bgp_dns_proto_rawDescGZIP(), []int{1}
}

type ClearCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClearedCount  uint64                 `protobuf:"varint,1,opt,name=cleared_count,json=clearedCount,proto3" json:"cleared_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCacheResponse) Reset() {
	*x = ClearCacheResponse{}
	mi := &file_proto_api_bgp_dns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCacheResponse) ProtoMessage() {}

func (x *ClearCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_bgp_dns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCacheResponse.ProtoReflect.Descriptor instead.
func (*ClearCacheResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_bgp_dns_proto_rawDescGZIP(), []int{2}
}

func (x *ClearCacheResponse) GetClearedCount() uint64 {
	if x != nil {
		return x.ClearedCount
	}
	return 0
}

type ListCacheEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Fqdn          string                 `protobuf:"bytes,2,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	Addr          []string               `protobuf:"bytes,3,rep,name=addr,proto3" json:"addr,omitempty"`
	Generation    string                 `protobuf:"bytes,4,opt,name=generation,proto3" json:"generation,omitempty"`
	Ttl           int64                  `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Expiration    int64                  `protobuf:"varint,6,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Fails         uint64                 `protobuf:"varint,7,opt,name=fails,proto3" json:"fails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCacheEntriesResponse) Reset() {
	*x = ListCacheEntriesResponse{}
	mi := &file_proto_api_bgp_dns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCacheEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCacheEntriesResponse) ProtoMessage() {}

func (x *ListCacheEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_bgp_dns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCacheEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListCacheEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_bgp_dns_proto_rawDescGZIP(), []int{3}
}

func (x *ListCacheEntriesResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListCacheEntriesResponse) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *ListCacheEntriesResponse) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *ListCacheEntriesResponse) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *ListCacheEntriesResponse) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *ListCacheEntriesResponse) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *ListCacheEntriesResponse) GetFails() uint64 {
	if x != nil {
		return x.Fails
	}
	return 0
}

var File_proto_api_bgp_dns_proto protoreflect.FileDescriptor

const file_proto_api_bgp_dns_proto_rawDesc = "" +
	"\n" +
	"\x17proto/api/bgp-dns.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n" +
	"\x17ListCacheEntriesRequest\"\x15\n" +
	"\x11ClearCacheRequest\"-\n" +
	"\x12ClearCacheResponse\x12\x17\n" +
	"\fcleared_count\x18\x01 \x01(\x04R\fclearedCount\"\xbe\x01\n" +
	"\x18ListCacheEntriesResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04fqdn\x18\x02 \x01(\tR\x04fqdn\x12\x12\n" +
	"\x04addr\x18\x03 \x03(\tR\x04addr\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\tR\n" +
	"generation\x12\x10\n" +
	"\x03ttl\x18\x05 \x01(\x03R\x03ttl\x12\x1e\n" +
	"\n" +
	"expiration\x18\x06 \x01(\x03R\n" +
	"expiration\x12\x14\n" +
	"\x05fails\x18\a \x01(\x04R\x05fails2\x8a\x01\n" +
	"\rBgpDnsService\x12K\n" +
	"\x10ListCacheEntries\x12\x16.google.protobuf.Empty\x1a\x1d.api.ListCacheEntriesResponse0\x01\x12,\n" +
	"\n" +
	"ClearCache\x12\x16.api.ClearCacheRequest\x1a\x17.api.ClearCacheResponseB\"Z github.com/red55/bgp-dns/api;apib\x06proto3"

var (
	file_proto_api_bgp_dns_proto_rawDescOnce sync.Once
	file_proto_api_bgp_dns_proto_rawDescData []byte
)

func file_proto_api_bgp_dns_proto_rawDescGZIP() []byte {
	file_proto_api_bgp_dns_proto_rawDescOnce.Do(func() {
		file_proto_api_bgp_dns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_bgp_dns_proto_rawDesc), len(file_proto_api_bgp_dns_proto_rawDesc)))
	})
	return file_proto_api_bgp_dns_proto_rawDescData
}

var file_proto_api_bgp_dns_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_api_bgp_dns_proto_goTypes = []any{
	(*ListCacheEntriesRequest)(nil),  // 0: api.ListCacheEntriesRequest
	(*ClearCacheRequest)(nil),        // 1: api.ClearCacheRequest
	(*ClearCacheResponse)(nil),       // 2: api.ClearCacheResponse
	(*ListCacheEntriesResponse)(nil), // 3: api.ListCacheEntriesResponse
	(*emptypb.Empty)(nil),            // 4: google.protobuf.Empty
}
var file_proto_api_bgp_dns_proto_depIdxs = []int32{
	4, // 0: api.BgpDnsService.ListCacheEntries:input_type -> google.protobuf.Empty
	1, // 1: api.BgpDnsService.ClearCache:input_type -> api.ClearCacheRequest
	3, // 2: api.BgpDnsService.ListCacheEntries:output_type -> api.ListCacheEntriesResponse
	2, // 3: api.BgpDnsService.ClearCache:output_type -> api.ClearCacheResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_bgp_dns_proto_init() }
func file_proto_api_bgp_dns_proto_init() {
	if File_proto_api_bgp_dns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_bgp_dns_proto_rawDesc), len(file_proto_api_bgp_dns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_bgp_dns_proto_goTypes,
		DependencyIndexes: file_proto_api_bgp_dns_proto_depIdxs,
		MessageInfos:      file_proto_api_bgp_dns_proto_msgTypes,
	}.Build()
	File_proto_api_bgp_dns_proto = out.File
	file_proto_api_bgp_dns_proto_goTypes = nil
	file_proto_api_bgp_dns_proto_depIdxs = nil
}
