// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/api/bgp-dns.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BgpDnsService_ListCacheEntries_FullMethodName = "/api.BgpDnsService/ListCacheEntries"
	BgpDnsService_ClearCache_FullMethodName       = "/api.BgpDnsService/ClearCache"
	BgpDnsService_ReloadList_FullMethodName       = "/api.BgpDnsService/ReloadList"
)

// BgpDnsServiceClient is the client API for BgpDnsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BgpDnsServiceClient interface {
	ListCacheEntries(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListCacheEntriesResponse], error)
	ClearCache(ctx context.Context, in *ClearCacheRequest, opts ...grpc.CallOption) (*ClearCacheResponse, error)
	ReloadList(ctx context.Context, in *ReloadListRequest, opts ...grpc.CallOption) (*ReloadListResponse, error)
}

type bgpDnsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBgpDnsServiceClient(cc grpc.ClientConnInterface) BgpDnsServiceClient {
	return &bgpDnsServiceClient{cc}
}

func (c *bgpDnsServiceClient) ListCacheEntries(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListCacheEntriesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BgpDnsService_ServiceDesc.Streams[0], BgpDnsService_ListCacheEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ListCacheEntriesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BgpDnsService_ListCacheEntriesClient = grpc.ServerStreamingClient[ListCacheEntriesResponse]

func (c *bgpDnsServiceClient) ClearCache(ctx context.Context, in *ClearCacheRequest, opts ...grpc.CallOption) (*ClearCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearCacheResponse)
	err := c.cc.Invoke(ctx, BgpDnsService_ClearCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bgpDnsServiceClient) ReloadList(ctx context.Context, in *ReloadListRequest, opts ...grpc.CallOption) (*ReloadListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadListResponse)
	err := c.cc.Invoke(ctx, BgpDnsService_ReloadList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BgpDnsServiceServer is the server API for BgpDnsService service.
// All implementations must embed UnimplementedBgpDnsServiceServer
// for forward compatibility.
type BgpDnsServiceServer interface {
	ListCacheEntries(*emptypb.Empty, grpc.ServerStreamingServer[ListCacheEntriesResponse]) error
	ClearCache(context.Context, *ClearCacheRequest) (*ClearCacheResponse, error)
	ReloadList(context.Context, *ReloadListRequest) (*ReloadListResponse, error)
	mustEmbedUnimplementedBgpDnsServiceServer()
}

// UnimplementedBgpDnsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBgpDnsServiceServer struct{}

func (UnimplementedBgpDnsServiceServer) ListCacheEntries(*emptypb.Empty, grpc.ServerStreamingServer[ListCacheEntriesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListCacheEntries not implemented")
}
func (UnimplementedBgpDnsServiceServer) ClearCache(context.Context, *ClearCacheRequest) (*ClearCacheResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearCache not implemented")
}
func (UnimplementedBgpDnsServiceServer) ReloadList(context.Context, *ReloadListRequest) (*ReloadListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadList not implemented")
}
func (UnimplementedBgpDnsServiceServer) mustEmbedUnimplementedBgpDnsServiceServer() {}
func (UnimplementedBgpDnsServiceServer) testEmbeddedByValue()                       {}

// UnsafeBgpDnsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BgpDnsServiceServer will
// result in compilation errors.
type UnsafeBgpDnsServiceServer interface {
	mustEmbedUnimplementedBgpDnsServiceServer()
}

func RegisterBgpDnsServiceServer(s grpc.ServiceRegistrar, srv BgpDnsServiceServer) {
	// If the following call pancis, it indicates UnimplementedBgpDnsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BgpDnsService_ServiceDesc, srv)
}

func _BgpDnsService_ListCacheEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BgpDnsServiceServer).ListCacheEntries(m, &grpc.GenericServerStream[emptypb.Empty, ListCacheEntriesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BgpDnsService_ListCacheEntriesServer = grpc.ServerStreamingServer[ListCacheEntriesResponse]

func _BgpDnsService_ClearCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpDnsServiceServer).ClearCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpDnsService_ClearCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpDnsServiceServer).ClearCache(ctx, req.(*ClearCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BgpDnsService_ReloadList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BgpDnsServiceServer).ReloadList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BgpDnsService_ReloadList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BgpDnsServiceServer).ReloadList(ctx, req.(*ReloadListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BgpDnsService_ServiceDesc is the grpc.ServiceDesc for BgpDnsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BgpDnsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.BgpDnsService",
	HandlerType: (*BgpDnsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClearCache",
			Handler:    _BgpDnsService_ClearCache_Handler,
		},
		{
			MethodName: "ReloadList",
			Handler:    _BgpDnsService_ReloadList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListCacheEntries",
			Handler:       _BgpDnsService_ListCacheEntries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/api/bgp-dns.proto",
}
